---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: auth-api-secrets
  namespace: default
spec:
  encryptedData:
    ALGORITHM: AgBTbf7k0xnwfxSyQJ7QozRgqeFjek2V036yBRJDuyFdRWOPQgt2HoacPY0xlR76hFPXnHkAHUT8FtzMy2v2hWkrx4rRHZFiRNMCiVt9WO6P1qn/msl6YuQZLzUuXC3ne0yQHi9HCf9qo8u2Y7Ds8WJgeTGrKwibYhjOQNVpfgoSEH0eFQbcgKKmdHxMI7PvJnpl2mwnwOcUnqnUVCRMcZARelcB0RjY4nPkRUd+iWz+57oFXdOKTClTlIVLM7rzK+Hdy1Aw/i92+b934KiTrDvJ2TFujyoWJX2T9A+juErseLJNhQg38aXD92LvKPGcFaYst5rIc3V4bzhq8UkaMVH0+579rf9lE4VuS8hPurl2NChGT7zl90m/HndVdbEg1l1joBCgMmnBO60lvGPPIVJXdjTjYu5ar2/Ofl7R+AEuUc7h0qBHW7vAdF8ZRU/NPYaWwLWarxEoIxw2NXytlXrMCvBu+QZGY55i/I4TkjATLbj5e4sz8tN666hDhsUwuPtaeJYFgP+XZfbiN84p/tbPyH7oSVwFdxoKXgIbdB3t2bxI2UY0SWUYospvRiG0IQnPudupRHEUBim6OWPbMadQtL9G0w7p7CKbjsGubd8YasLUEu32w31AwKZe/k456sAMnAYVosiY3kZH5HZyyZvUVzYHkga3kPfLTGz5Zvo+80QDdRsLD99FOLsvvVNWHaArB+qc8g==
    SECRET_KEY: AgCnfmDCdflbvEWGzZAoP7rhQJw0nv4DTAezhEn0aI0Kz9tEcW+7hjUPG599In3bYtkLSAlbdHyYgUpCRSirKn/n44TpIdn5A1FURCV9e89zN6wBEU34a8RVN3ex7lLfqApLfEPmToMH3hN3OHt725Tis5Tq6uhiAHwWvF5FTk8LkydLM7eU6qGN7xY6X/UbjaI3NV8Jn5aoLHJGPi4h0MF/gSgMLx85cOj54kyzgUS0FWwqi4z/2Lwj7RllM0OjDAI2oJzBYs7kKngfsXRNMpsNga8LFeuYeN6rs8UP1D9fVCgfjbVukgqaF03EB0pj+e5bkeHVnuqO+GuziLlwJzE5Hi7ObX5otUkW8rvl2bji1ffeWA2E/dwrtrRiAXXg+lfjyB6SNtQb9Eql14la6mZtSSZ7cnbr9wIQ57a0ZjwL74jbHl4GC9FfkYJmbIVLyHu3s/QFRaKsN4qCuIL7faJzpnnxDk124s6kyJ51WMQZqSsZ37HclqZRZgXm3S0umhy3lPz0tYTg02XWHYfW2f/JVOPNGOAvBV7cDrqLRli9uH9vOI1Db3zkOQoGW7SNEdVMntyJWw0RscNFUSGfUGMuEIoe9RMBOW9CO40VQCcqm85lCzYvKWmZPtOgy0EAfHnZuoRiFSKmdd5J6GwDAOEHFAwfkBPp3Zi9U5GqtfeH4jjqiBTOiwy9WuAsgxPba9y28rhJ8YeF3/lvLO/YAYVtbFbO+z5djIQk5SznwiWHP7m8xlvFM0qZmoZCBon7sgCZLuoLSQ7o38e4Rx0PaF0tCA==
  template:
    metadata:
      name: auth-api-secrets
      namespace: default
