# kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# - observability
# - namespaces.yaml
resources:
- databases/user_db/user-db.yaml
- databases/user_db/user-db-pv.yaml
- databases/user_db/user-db-pvc.yaml
- databases/post_db/post-db.yaml
- databases/post_db/post-db-pv.yaml
- databases/post_db/post-db-pvc.yaml
- databases/comment_db/comment-db.yaml
- databases/comment_db/comment-db-pv.yaml
- databases/comment_db/comment-db-pvc.yaml
- jobs/user_db_migration.yaml
- jobs/post_db_migration.yaml
- jobs/comment_db_migration.yaml
- services/user/user-api-hpa.yaml
- services/user/user-api.yaml
- services/post/post-api-hpa.yaml
- services/post/post-api.yaml
- services/comment/comment-api-hpa.yaml
- services/comment/comment-api.yaml
- services/auth/auth-api-hpa.yaml
- services/auth/auth-api.yaml
- secrets/user-api-sealed.yaml
- secrets/post-api-sealed.yaml
- secrets/comment-api-sealed.yaml
- secrets/auth-api-sealed.yaml
- argocd/argo_application.yaml
- argocd/argo_ingress.yaml
- ingress.yaml
images:
- name: louischatain25/auth-api
  newName: louischatain25/auth-api
  newTag: 0f6bef4e3d221c93c9cba8b4a4ba2a1ca1a98511
- name: louischatain25/comment-api
  newName: louischatain25/comment-api
  newTag: ffb84cca02af4eeb5c63d8e43af7b33ee6aa3d42
- name: louischatain25/post-api
  newName: louischatain25/post-api
  newTag: fda84bc3658c4d5e894834e0b676a4dfb41e645c
- name: louischatain25/user-api
  newName: louischatain25/user-api
  newTag: e8604696d6096168f7dc55f2c6b0ded77cbf6856
